@startuml
!include <logos/flutter>
!include <logos/spring>
!include <logos/mysql>
!include <logos/redis>
!include <logos/nginx>
!include <logos/docker>
!include <logos/github>
!include <logos/google>
component "<$flutter>\nFlutter" as f
component "<$spring>\nSpring Boot" as s
component "<$mysql>\nMySQL" as m
component "<$redis>\nRedis" as r
component "<$nginx>\nNginx" as n
component "<$docker>\nDocker" as d
component "<$github>\nGitHub Actions" as g
component "<$google>\nGemini" as ge
@enduml
