@startuml
left to right direction
skinparam packageStyle rectangle
skinparam actorStyle awesome
skinparam defaultFontName "Times New Roman"
skinparam usecase {
  BackgroundColor White
  BorderColor Black
}

title UC05 - Theo dõi lộ trình trị liệu

actor "Bệnh nhân" as Patient
actor "Bác sĩ" as Therapist

rectangle "Hệ thống ReConnect MindHealth" {
  usecase "Theo dõi lộ trình trị liệu" as UC05
  usecase "Xem lộ trình\ntrị liệu" as UC051
  usecase "Xem Thang\nsợ hãi" as UC052
  usecase "Xem tiến độ\nđiều trị" as UC053
  usecase "Xem các bài\nđang mở" as UC054
  usecase "Xem lịch sử bài\nđã hoàn thành" as UC055
  usecase "Nhận nhắc nhở\nđiều trị" as UC056
}

Patient --> UC05
Therapist --> UC05

UC05 ..> UC051 : <<include>>
UC05 ..> UC052 : <<include>>
UC05 ..> UC053 : <<include>>
UC05 ..> UC054 : <<include>>
UC05 ..> UC055 : <<include>>
UC05 ..> UC056 : <<include>>

@enduml
