@startuml
left to right direction
skinparam actorStyle awesome
skinparam defaultFontName Arial
skinparam usecase {
  BackgroundColor White
  BorderColor Black
}

title Biểu đồ phân rã use case Khách

actor "Khách" as Guest

usecase "Quản lý tài khoản,\nhồ sơ và danh tính ẩn danh" as G_ACC
usecase "Đánh giá LSAS và\nphân luồng lâm sàng" as G_LSAS

usecase "Trải nghiệm ở\nchế độ ẩn danh" as G1
usecase "Chọn biệt danh" as G2
usecase "Chọn ảnh đại diện ảo" as G3
usecase "Hoàn thành cổng\nchuyển đổi" as G4
usecase "Liên kết email\nvà mật khẩu" as G5
usecase "Khai báo hồ sơ y tế\ntối thiểu" as G6
usecase "Chuyển thành\nBệnh nhân" as G7

usecase "Thực hiện LSAS\nthử nghiệm" as G8
usecase "Xem yêu cầu\nchuyển đổi tài khoản" as G9

Guest --> G_ACC
Guest --> G_LSAS

G_ACC ..> G1 : <<include>>
G_ACC ..> G4 : <<include>>
G1 ..> G2 : <<include>>
G1 ..> G3 : <<include>>
G4 ..> G5 : <<include>>
G4 ..> G6 : <<include>>
G4 ..> G7 : <<include>>

G_LSAS ..> G8 : <<include>>
G8 ..> G9 : <<extend>>

@enduml
