@startuml
skinparam defaultFontName "Times New Roman"
skinparam wrapWidth 200
skinparam NodePadding 20

|Bác sĩ|
start
:Mở màn hình xem trước phiên tư vấn;

|Hệ thống|
:Truy xuất dữ liệu lâm sàng của Bệnh nhân;
:Hiển thị tóm tắt hồ sơ lâm sàng;
:Hiển thị điểm LSAS gần nhất và xu hướng thay đổi;
:Hiển thị Thang sợ hãi và các bài thực hành gần đây;
:Hiển thị tóm tắt Nhật ký suy nghĩ và ghi chú liên quan;

|Bác sĩ|
:Xem thông tin và chuẩn bị nội dung phiên tư vấn;
stop
@enduml
