@startuml
skinparam defaultFontName "Times New Roman"
skinparam shadowing false
skinparam monochrome true
skinparam nodesep 80
skinparam ranksep 70
skinparam usecaseFontSize 14
left to right direction
title UC03 - Đăng nhập

actor "Người dùng" as A

usecase "Form_DangNhap" as B1
usecase "Form_QuenMatKhau" as B2

usecase "ctrl_Auth" as C1
usecase "ctrl_TokenManager" as C2

usecase "Ent_User" as E1
usecase "Ent_PatientProfile" as E2
usecase "Ent_TherapistProfile" as E3

A -- B1
A -- B2

B1 -- C1
B2 -- C1

C1 -- C2
C1 -- E1
C1 -- E2
C1 -- E3
C2 -- E1

B1 -[hidden]-> B2
B2 -[hidden]-> C1
C1 -[hidden]-> C2
C2 -[hidden]-> E1
E1 -[hidden]down-> E2
E2 -[hidden]down-> E3
@enduml
