@startuml
skinparam defaultFontName "Times New Roman"
skinparam shadowing false
skinparam monochrome true
skinparam nodesep 80
skinparam ranksep 70
skinparam usecaseFontSize 14
left to right direction
title UC04 - Điểm danh cảm xúc

actor "Bệnh nhân" as A

usecase "Form_DailyCheckin" as B1
usecase "Form_SafetyGate" as B2
usecase "Form_KhanCap" as B3

usecase "ctrl_CheckinSubmit" as C1
usecase "ctrl_SafetyGate" as C2
usecase "ctrl_Routing" as C3

usecase "Ent_UserMood" as E1
usecase "Ent_PatientProfile" as E2
usecase "Ent_Journal" as E3

A -- B1
A -- B2

B1 -- C1
B2 -- C2
B3 -- C2

C1 -- C2
C2 -- C3

C1 -- E1
C2 -- E1
C2 -- E2
C3 -- E1
C3 -- E3

B1 -[hidden]-> B2
B2 -[hidden]-> B3
B3 -[hidden]-> C1
C1 -[hidden]-> C2
C2 -[hidden]-> C3
C3 -[hidden]-> E1
E1 -[hidden]down-> E2
E2 -[hidden]down-> E3
@enduml
