@startuml
skinparam defaultFontName "Times New Roman"
skinparam shadowing false
skinparam monochrome true
skinparam nodesep 80
skinparam ranksep 70
skinparam usecaseFontSize 14
left to right direction
title UC05 - Viết Nhật ký suy nghĩ có hỗ trợ AI

actor "Bệnh nhân" as A

usecase "Form_ThoughtRecord" as B1
usecase "Form_AiSuggest" as B2

usecase "ctrl_JournalWrite" as C1
usecase "ctrl_AiAnalysis" as C2
usecase "ctrl_RiskDetect" as C3

usecase "Ent_Journal" as E1
usecase "Ent_PatientProfile" as E2

A -- B1
A -- B2

B1 -- C1
B2 -- C2

C1 -- C2
C2 -- C3

C1 -- E1
C3 -- E1
C3 -- E2

B1 -[hidden]-> B2
B2 -[hidden]-> C1
C1 -[hidden]-> C2
C2 -[hidden]-> C3
C3 -[hidden]-> E1
E1 -[hidden]down-> E2
@enduml
