@startuml
skinparam defaultFontName "Times New Roman"
skinparam shadowing false
skinparam monochrome true
skinparam nodesep 80
skinparam ranksep 80
left to right direction
title UC07 - Đặt lịch và tư vấn từ xa

actor "Bệnh nhân" as Patient
actor "Bác sĩ" as Therapist

usecase "Form_DatLich" as B1
usecase "Form_LichHen" as B2
usecase "ctrl_DatLich" as C1
usecase "ctrl_LichHen" as C2

usecase "Ent_Appointment" as E1
usecase "Ent_TherapistScheduleSlot" as E2
usecase "Ent_PatientProfile" as E3
usecase "Ent_TherapistProfile" as E4

Patient -- B1
Patient -- B2
Therapist -- B2

B1 -- C1
B2 -- C2
C1 -- C2

C1 -- E2
C1 -- E3
C1 -- E4
C2 -- E1
C2 -- E3
C2 -- E4
@enduml
