@startuml
skinparam defaultFontName "Times New Roman"
skinparam shadowing false
skinparam monochrome true
skinparam nodesep 80
skinparam ranksep 80
left to right direction
title UC08 - Thực hành Thử nghiệm hành vi

actor "Bệnh nhân" as Patient
actor "Bác sĩ" as Therapist

usecase "Form_Roadmap" as B1
usecase "Form_ThietLapThuNghiem" as B2
usecase "Form_TongKetThuNghiem" as B3
usecase "ctrl_FearLadder" as C1
usecase "ctrl_BehavioralExperiment" as C2

usecase "Ent_FearLadderItem" as E1
usecase "Ent_BehavioralExperiment" as E2
usecase "Ent_PatientProfile" as E3

Patient -- B1
Patient -- B2
Patient -- B3
Therapist -- B1

B1 -- C1
B2 -- C2
B3 -- C2
C1 -- C2

C1 -- E1
C1 -- E3
C2 -- E1
C2 -- E2
C2 -- E3
@enduml
